from pymongo import MongoClient
import os
from dotenv import load_dotenv

load_dotenv()

MONGODB_URI = os.getenv("MONGODB_URI")
if not MONGODB_URI:
    raise ValueError("MONGODB_URI is not set. Copy .env.example to .env and add your MongoDB URI.")

client = MongoClient(MONGODB_URI)

db = client["Vitabit-Database"]
collection = db["supplements"]


data = [{'name': 'Vitamin A',
  'category': 'Vitamin',
  'keywords': ['retinol', 'beta carotene', 'eye health'],
  'benefit': 'Vision support, immune function, and skin health',
  'how_to_take': 'Take once daily with a meal that contains fat',
  'male_daily_intake': '900 mcg RAE/day',
  'female_daily_intake': '700 mcg RAE/day',
  'intake_note': 'Avoid high-dose retinol during pregnancy unless prescribed. UL: 3000 mcg '
                 'RAE/day.',
  'image_url': '/static/images/vitamin-a.svg'},
 {'name': 'Vitamin B1',
  'category': 'Vitamin',
  'keywords': ['thiamin', 'thiamine', 'energy metabolism'],
  'benefit': 'Carbohydrate metabolism and nerve support',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '1.2 mg/day',
  'female_daily_intake': '1.1 mg/day',
  'intake_note': 'Often included in B-complex supplements. Needs may be higher with heavy alcohol '
                 'use.',
  'image_url': '/static/images/vitamin-b1.svg'},
 {'name': 'Vitamin B2',
  'category': 'Vitamin',
  'keywords': ['riboflavin', 'migraine support', 'energy'],
  'benefit': 'Energy production and antioxidant support',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '1.3 mg/day',
  'female_daily_intake': '1.1 mg/day',
  'intake_note': 'May turn urine bright yellow. High-dose use is sometimes discussed for '
                 'migraines.',
  'image_url': '/static/images/vitamin-b2.svg'},
 {'name': 'Vitamin B3',
  'category': 'Vitamin',
  'keywords': ['niacin', 'nicotinamide', 'nad'],
  'benefit': 'Energy metabolism and skin support',
  'how_to_take': 'Take with food to reduce stomach upset',
  'male_daily_intake': '16 mg NE/day',
  'female_daily_intake': '14 mg NE/day',
  'intake_note': 'High-dose niacin can cause flushing and should not be self-started for '
                 'cholesterol management.',
  'image_url': '/static/images/vitamin-b3.svg'},
 {'name': 'Vitamin B5',
  'category': 'Vitamin',
  'keywords': ['pantothenic acid', 'coenzyme a'],
  'benefit': 'Hormone synthesis and energy metabolism',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '5 mg/day',
  'female_daily_intake': '5 mg/day',
  'intake_note': 'Deficiency is rare, but it is commonly included in multivitamins and B-complex '
                 'products.',
  'image_url': '/static/images/vitamin-b5.svg'},
 {'name': 'Vitamin B6',
  'category': 'Vitamin',
  'keywords': ['pyridoxine', 'p5p', 'nerve support'],
  'benefit': 'Brain health, neurotransmitter production, and immune support',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '1.3-1.7 mg/day',
  'female_daily_intake': '1.3-1.5 mg/day',
  'intake_note': 'Long-term high doses can cause nerve problems. Avoid chronic megadosing.',
  'image_url': '/static/images/vitamin-b6.svg'},
 {'name': 'Vitamin B7',
  'category': 'Vitamin',
  'keywords': ['biotin', 'hair', 'nails'],
  'benefit': 'Energy metabolism and hair, skin, and nail support',
  'how_to_take': 'Take once daily with or without food',
  'male_daily_intake': '30 mcg/day',
  'female_daily_intake': '30 mcg/day',
  'intake_note': 'High-dose biotin can interfere with lab tests, including thyroid and troponin '
                 'results.',
  'image_url': '/static/images/vitamin-b7.svg'},
 {'name': 'Vitamin B9',
  'category': 'Vitamin',
  'keywords': ['folate', 'folic acid', 'methylfolate', 'prenatal'],
  'benefit': 'DNA synthesis and red blood cell formation',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '400 mcg DFE/day',
  'female_daily_intake': '400 mcg DFE/day',
  'intake_note': 'Important before and during pregnancy. Excess folic acid can mask B12 '
                 'deficiency.',
  'image_url': '/static/images/vitamin-b9.svg'},
 {'name': 'Vitamin B12',
  'category': 'Vitamin',
  'keywords': ['cobalamin', 'methylcobalamin', 'cyanocobalamin', 'vegan'],
  'benefit': 'Nerve health, DNA synthesis, and red blood cell production',
  'how_to_take': 'Take once daily; sublingual or oral forms both work for many users',
  'male_daily_intake': '2.4 mcg/day',
  'female_daily_intake': '2.4 mcg/day',
  'intake_note': 'Vegetarians, vegans, and older adults are more likely to need supplementation.',
  'image_url': '/static/images/vitamin-b12.svg'},
 {'name': 'Vitamin C',
  'category': 'Vitamin',
  'keywords': ['ascorbic acid', 'immune support', 'antioxidant'],
  'benefit': 'Immune support and antioxidant protection',
  'how_to_take': 'Take 1 tablet daily after a meal',
  'male_daily_intake': '90 mg/day',
  'female_daily_intake': '75 mg/day',
  'intake_note': 'UL: 2000 mg/day. High doses may cause stomach upset or diarrhea.',
  'image_url': '/static/images/vitamin-c.svg'},
 {'name': 'Vitamin D3',
  'category': 'Vitamin',
  'keywords': ['cholecalciferol', 'bone health', 'sunshine vitamin'],
  'benefit': 'Bone health, immune support, and mood support',
  'how_to_take': 'Take with a meal containing fat',
  'male_daily_intake': '600 IU/day (15 mcg/day)',
  'female_daily_intake': '600 IU/day (15 mcg/day)',
  'intake_note': 'Adults 71+ often use 800 IU/day. Long-term use is best guided by a 25(OH)D blood '
                 'test.',
  'image_url': '/static/images/vitamin-d3.svg'},
 {'name': 'Vitamin E',
  'category': 'Vitamin',
  'keywords': ['alpha tocopherol', 'antioxidant', 'skin'],
  'benefit': 'Antioxidant support and cell membrane protection',
  'how_to_take': 'Take once daily with a meal containing fat',
  'male_daily_intake': '15 mg/day',
  'female_daily_intake': '15 mg/day',
  'intake_note': 'High doses may increase bleeding risk, especially with blood thinners.',
  'image_url': '/static/images/vitamin-e.svg'},
 {'name': 'Vitamin K',
  'category': 'Vitamin',
  'keywords': ['phylloquinone', 'menaquinone', 'k1', 'k2'],
  'benefit': 'Bone health and normal blood clotting',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '120 mcg/day',
  'female_daily_intake': '90 mcg/day',
  'intake_note': 'If you take warfarin or another anticoagulant, keep intake consistent and ask '
                 'your clinician.',
  'image_url': '/static/images/vitamin-k.svg'},
 {'name': 'Choline',
  'category': 'Vitamin-like Nutrient',
  'keywords': ['brain health', 'liver support', 'prenatal nutrient'],
  'benefit': 'Brain function, liver health, and cell membrane support',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '550 mg/day',
  'female_daily_intake': '425 mg/day',
  'intake_note': 'Not a vitamin by strict definition, but commonly included in nutrition guidance '
                 'and prenatal support.',
  'image_url': '/static/images/choline.svg'},
 {'name': 'Calcium',
  'category': 'Mineral',
  'keywords': ['bone health', 'teeth', 'calcium citrate', 'calcium carbonate'],
  'benefit': 'Bone health, muscle contraction, and nerve signaling',
  'how_to_take': 'Split larger doses and take with food unless using citrate',
  'male_daily_intake': '1000-1200 mg/day',
  'female_daily_intake': '1000-1200 mg/day',
  'intake_note': 'Calcium carbonate absorbs best with food. Avoid taking it at the same time as '
                 'iron.',
  'image_url': '/static/images/calcium.svg'},
 {'name': 'Magnesium',
  'category': 'Mineral',
  'keywords': ['sleep', 'muscle', 'magnesium glycinate', 'magnesium citrate'],
  'benefit': 'Muscle relaxation, better sleep, and nerve function',
  'how_to_take': 'Take 1 capsule before bedtime',
  'male_daily_intake': '400-420 mg/day',
  'female_daily_intake': '310-320 mg/day',
  'intake_note': 'Supplemental UL is 350 mg/day from non-food sources because higher doses can '
                 'cause diarrhea.',
  'image_url': '/static/images/magnesium.svg'},
 {'name': 'Iron',
  'category': 'Mineral',
  'keywords': ['ferritin', 'anemia', 'ferrous sulfate', 'ferrous bisglycinate'],
  'benefit': 'Oxygen transport and red blood cell production',
  'how_to_take': 'Take on an empty stomach if tolerated, or with a light meal if needed',
  'male_daily_intake': '8 mg/day',
  'female_daily_intake': '18 mg/day',
  'intake_note': 'Iron should ideally be matched to labs. Take away from calcium, coffee, and tea '
                 'for better absorption.',
  'image_url': '/static/images/iron.svg'},
 {'name': 'Zinc',
  'category': 'Mineral',
  'keywords': ['immune', 'wound healing', 'zinc picolinate', 'zinc citrate'],
  'benefit': 'Immune support, wound healing, and skin health',
  'how_to_take': 'Take with food to reduce nausea',
  'male_daily_intake': '11 mg/day',
  'female_daily_intake': '8 mg/day',
  'intake_note': 'Long-term high-dose zinc can reduce copper status. UL: 40 mg/day.',
  'image_url': '/static/images/zinc.svg'},
 {'name': 'Potassium',
  'category': 'Mineral',
  'keywords': ['electrolyte', 'blood pressure', 'muscle cramps'],
  'benefit': 'Fluid balance, muscle function, and blood pressure support',
  'how_to_take': 'Use supplements only with caution; food sources are preferred',
  'male_daily_intake': '3400 mg/day',
  'female_daily_intake': '2600 mg/day',
  'intake_note': 'Potassium supplements can be risky in kidney disease or with certain blood '
                 'pressure medicines.',
  'image_url': '/static/images/potassium.svg'},
 {'name': 'Selenium',
  'category': 'Mineral',
  'keywords': ['thyroid', 'antioxidant', 'selenometionine'],
  'benefit': 'Thyroid hormone metabolism and antioxidant defense',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '55 mcg/day',
  'female_daily_intake': '55 mcg/day',
  'intake_note': 'Too much selenium can cause brittle nails, hair loss, and stomach upset. UL: 400 '
                 'mcg/day.',
  'image_url': '/static/images/selenium.svg'},
 {'name': 'Iodine',
  'category': 'Mineral',
  'keywords': ['thyroid', 'kelp', 'iodide'],
  'benefit': 'Thyroid hormone production and metabolic support',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '150 mcg/day',
  'female_daily_intake': '150 mcg/day',
  'intake_note': 'Both low and high iodine intake can affect thyroid health. Use caution with '
                 'thyroid disease.',
  'image_url': '/static/images/iodine.svg'},
 {'name': 'Copper',
  'category': 'Mineral',
  'keywords': ['red blood cells', 'iron metabolism', 'trace mineral'],
  'benefit': 'Iron metabolism, connective tissue support, and antioxidant enzymes',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '900 mcg/day',
  'female_daily_intake': '900 mcg/day',
  'intake_note': 'Copper balance matters most when supplementing zinc long term.',
  'image_url': '/static/images/copper.svg'},
 {'name': 'Manganese',
  'category': 'Mineral',
  'keywords': ['bone formation', 'trace mineral', 'enzyme support'],
  'benefit': 'Bone formation and enzyme function',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '2.3 mg/day',
  'female_daily_intake': '1.8 mg/day',
  'intake_note': 'Usually covered by diet. Avoid unnecessary high-dose use.',
  'image_url': '/static/images/manganese.svg'},
 {'name': 'Chromium',
  'category': 'Mineral',
  'keywords': ['blood sugar', 'chromium picolinate', 'glucose metabolism'],
  'benefit': 'Glucose metabolism and insulin support',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '35 mcg/day',
  'female_daily_intake': '25 mcg/day',
  'intake_note': 'Commonly marketed for blood sugar support, but effects vary and do not replace '
                 'medical care.',
  'image_url': '/static/images/chromium.svg'},
 {'name': 'Molybdenum',
  'category': 'Mineral',
  'keywords': ['trace mineral', 'enzyme cofactor'],
  'benefit': 'Enzyme support for sulfur amino acid metabolism',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': '45 mcg/day',
  'female_daily_intake': '45 mcg/day',
  'intake_note': 'Needed in very small amounts and usually adequate from diet.',
  'image_url': '/static/images/molybdenum.svg'},
 {'name': 'Phosphorus',
  'category': 'Mineral',
  'keywords': ['bone mineral', 'energy production', 'phosphate'],
  'benefit': 'Bone structure, cellular energy, and acid-base balance',
  'how_to_take': 'Usually obtained through diet; supplement only when indicated',
  'male_daily_intake': '700 mg/day',
  'female_daily_intake': '700 mg/day',
  'intake_note': 'Most adults get enough from food. Excess intake can be a problem in kidney '
                 'disease.',
  'image_url': '/static/images/phosphorus.svg'},
 {'name': 'Omega-3 Fish Oil',
  'category': 'Essential Fatty Acid',
  'keywords': ['epa', 'dha', 'fish oil', 'triglycerides', 'heart health'],
  'benefit': 'Heart health, triglyceride support, and anti-inflammatory support',
  'how_to_take': 'Take with meals, ideally split into 1 to 2 doses if using higher amounts',
  'male_daily_intake': 'No established RDA; many supplements provide 250-1000 mg EPA+DHA/day',
  'female_daily_intake': 'No established RDA; many supplements provide 250-1000 mg EPA+DHA/day',
  'intake_note': 'Use caution with bleeding disorders or blood thinners. Check EPA and DHA '
                 'content, not just total fish oil.',
  'image_url': '/static/images/omega-3.svg'},
 {'name': 'Coenzyme Q10',
  'category': 'Specialty Supplement',
  'keywords': ['coq10', 'ubiquinone', 'ubiquinol', 'mitochondria', 'statin support'],
  'benefit': 'Cellular energy production and heart support',
  'how_to_take': 'Take with a meal containing fat for better absorption',
  'male_daily_intake': 'No established RDA; common supplement range is 100-200 mg/day',
  'female_daily_intake': 'No established RDA; common supplement range is 100-200 mg/day',
  'intake_note': 'Often used by people taking statins, but it is still a supplement and not a '
                 'substitute for prescribed care.',
  'image_url': '/static/images/coenzyme-q10.svg'},
 {'name': 'Probiotics',
  'category': 'Gut Health Supplement',
  'keywords': ['gut health', 'microbiome', 'lactobacillus', 'bifidobacterium', 'digestive support'],
  'benefit': 'Digestive support and microbiome balance',
  'how_to_take': 'Take daily as directed on the strain-specific product label',
  'male_daily_intake': 'No established RDA; dose is strain-specific and often measured in CFU',
  'female_daily_intake': 'No established RDA; dose is strain-specific and often measured in CFU',
  'intake_note': 'Effects depend heavily on the strain and dose. Refrigeration depends on the '
                 'specific product, not all probiotics.',
  'image_url': '/static/images/probiotics.svg'},
 {'name': 'Prebiotic Fiber',
  'category': 'Gut Health Supplement',
  'keywords': ['inulin', 'prebiotic', 'fiber', 'regularity', 'gut'],
  'benefit': 'Regularity support and nourishment for beneficial gut bacteria',
  'how_to_take': 'Start with a small amount and increase slowly with plenty of water',
  'male_daily_intake': 'No established RDA; follow product serving size',
  'female_daily_intake': 'No established RDA; follow product serving size',
  'intake_note': 'Can cause bloating or gas if increased too quickly.',
  'image_url': '/static/images/prebiotic-fiber.svg'},
 {'name': 'Psyllium Husk',
  'category': 'Fiber Supplement',
  'keywords': ['metamucil', 'soluble fiber', 'cholesterol', 'constipation'],
  'benefit': 'Digestive regularity and cholesterol support',
  'how_to_take': 'Mix with plenty of water and drink immediately',
  'male_daily_intake': 'No established RDA; common use is 1 serving 1-3 times/day',
  'female_daily_intake': 'No established RDA; common use is 1 serving 1-3 times/day',
  'intake_note': 'Must be taken with adequate fluid. Separate from medications if instructed on '
                 'the label.',
  'image_url': '/static/images/psyllium-husk.svg'},
 {'name': 'Collagen Peptides',
  'category': 'Protein Supplement',
  'keywords': ['collagen', 'skin', 'joints', 'beauty supplement'],
  'benefit': 'Skin elasticity, joint support, and connective tissue support',
  'how_to_take': 'Mix into coffee, water, or smoothies once daily',
  'male_daily_intake': 'No established RDA; common use is 5-20 g/day',
  'female_daily_intake': 'No established RDA; common use is 5-20 g/day',
  'intake_note': 'This is a protein supplement, not a complete protein source. Product source may '
                 'be bovine, marine, or chicken.',
  'image_url': '/static/images/collagen.svg'},
 {'name': 'Creatine Monohydrate',
  'category': 'Performance Supplement',
  'keywords': ['creatine', 'muscle strength', 'exercise performance', 'gym'],
  'benefit': 'Strength, power output, and muscle performance support',
  'how_to_take': 'Take daily, with or without workouts; consistency matters more than timing',
  'male_daily_intake': 'No established RDA; common maintenance dose is 3-5 g/day',
  'female_daily_intake': 'No established RDA; common maintenance dose is 3-5 g/day',
  'intake_note': 'Generally taken with adequate hydration. Weight gain from increased water '
                 'storage can occur.',
  'image_url': '/static/images/creatine.svg'},
 {'name': 'Melatonin',
  'category': 'Sleep Supplement',
  'keywords': ['sleep', 'jet lag', 'circadian rhythm', 'bedtime'],
  'benefit': 'Sleep onset support and circadian rhythm adjustment',
  'how_to_take': 'Take 30 to 60 minutes before bedtime',
  'male_daily_intake': 'No established RDA; many products use 0.3-5 mg',
  'female_daily_intake': 'No established RDA; many products use 0.3-5 mg',
  'intake_note': 'Lower doses are often enough. May cause morning grogginess in some users.',
  'image_url': '/static/images/melatonin.svg'},
 {'name': 'Turmeric Curcumin',
  'category': 'Herbal Supplement',
  'keywords': ['curcumin', 'turmeric', 'joint comfort', 'inflammation'],
  'benefit': 'Joint comfort and anti-inflammatory support',
  'how_to_take': 'Take with food; some products include piperine for absorption',
  'male_daily_intake': 'No established RDA; follow product dosing',
  'female_daily_intake': 'No established RDA; follow product dosing',
  'intake_note': 'Can interact with blood thinners and may cause stomach upset in some users.',
  'image_url': '/static/images/turmeric-curcumin.svg'},
 {'name': 'Glucosamine Chondroitin',
  'category': 'Joint Support Supplement',
  'keywords': ['joint support', 'cartilage', 'osteoarthritis', 'msm'],
  'benefit': 'Joint comfort and cartilage support',
  'how_to_take': 'Take daily with food, often split into 2 to 3 doses depending on the product',
  'male_daily_intake': 'No established RDA; common use follows product label',
  'female_daily_intake': 'No established RDA; common use follows product label',
  'intake_note': 'Joint response can take several weeks. Shellfish-derived ingredients are common.',
  'image_url': '/static/images/glucosamine-chondroitin.svg'},
 {'name': 'Lutein',
  'category': 'Eye Health Supplement',
  'keywords': ['zeaxanthin', 'macula', 'eye health', 'screen fatigue'],
  'benefit': 'Eye health and macular support',
  'how_to_take': 'Take with a meal containing fat',
  'male_daily_intake': 'No established RDA; common use is 10-20 mg/day',
  'female_daily_intake': 'No established RDA; common use is 10-20 mg/day',
  'intake_note': 'Often paired with zeaxanthin in eye health formulas.',
  'image_url': '/static/images/lutein.svg'},
 {'name': 'Ashwagandha',
  'category': 'Herbal Supplement',
  'keywords': ['stress', 'adaptogen', 'sleep support', 'cortisol'],
  'benefit': 'Stress support and general wellness support',
  'how_to_take': 'Take once or twice daily depending on extract strength',
  'male_daily_intake': 'No established RDA; follow standardized extract dosing on the label',
  'female_daily_intake': 'No established RDA; follow standardized extract dosing on the label',
  'intake_note': 'Use caution with thyroid disorders, pregnancy, or sedating medications.',
  'image_url': '/static/images/ashwagandha.svg'},
 {'name': 'Berberine',
  'category': 'Specialty Supplement',
  'keywords': ['metabolic health', 'blood sugar', 'lipids', 'insulin support'],
  'benefit': 'Metabolic and blood sugar support',
  'how_to_take': 'Take with meals if tolerated',
  'male_daily_intake': 'No established RDA; follow product dosing',
  'female_daily_intake': 'No established RDA; follow product dosing',
  'intake_note': 'Can interact with medications and is not a replacement for diabetes treatment.',
  'image_url': '/static/images/berberine.svg'},
 {'name': 'Protein Powder',
  'category': 'Protein Supplement',
  'keywords': ['whey', 'plant protein', 'muscle recovery', 'shake'],
  'benefit': 'Protein intake support, satiety, and muscle recovery',
  'how_to_take': 'Mix with water or milk after workouts or as needed to meet protein goals',
  'male_daily_intake': 'No established RDA for supplements; total daily protein needs depend on '
                       'body size and activity',
  'female_daily_intake': 'No established RDA for supplements; total daily protein needs depend on '
                         'body size and activity',
  'intake_note': 'This helps fill protein gaps but should not replace a balanced diet.',
  'image_url': '/static/images/protein-powder.svg'},
 {'name': 'Multivitamin',
  'category': 'Multivitamin Formula',
  'keywords': ['daily multi', 'one daily', 'general wellness', 'foundational supplement'],
  'benefit': 'Broad nutrient coverage for daily baseline support',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': 'No single RDA; follow product label',
  'female_daily_intake': 'No single RDA; follow product label',
  'intake_note': 'Useful as a base layer, but formulas vary widely and should not replace targeted '
                 'treatment of deficiencies.',
  'image_url': '/static/images/multivitamin.svg'},
 {'name': "Women's Multivitamin",
  'category': 'Multivitamin Formula',
  'keywords': ["women's multi", 'iron support', "daily women's vitamin"],
  'benefit': "Baseline micronutrient support tailored to common women's formulas",
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': 'Not typically targeted',
  'female_daily_intake': 'No single RDA; follow product label',
  'intake_note': 'Often includes iron and higher folate, but formulas differ by brand and age '
                 'group.',
  'image_url': '/static/images/womens-multivitamin.svg'},
 {'name': "Men's Multivitamin",
  'category': 'Multivitamin Formula',
  'keywords': ["men's multi", "daily men's vitamin", "general men's wellness"],
  'benefit': "Baseline micronutrient support tailored to common men's formulas",
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': 'No single RDA; follow product label',
  'female_daily_intake': 'Not typically targeted',
  'intake_note': "Many men's formulas reduce or exclude iron unless specifically formulated "
                 'otherwise.',
  'image_url': '/static/images/mens-multivitamin.svg'},
 {'name': 'Prenatal Multivitamin',
  'category': 'Multivitamin Formula',
  'keywords': ['prenatal', 'pregnancy', 'folate', 'iron', 'dha prenatal'],
  'benefit': 'Pregnancy-focused nutrient support including folate and iron in many formulas',
  'how_to_take': 'Take daily with food, usually at the same time each day',
  'male_daily_intake': 'Not applicable',
  'female_daily_intake': 'No single RDA; follow prenatal product label and clinician guidance',
  'intake_note': 'Prenatal formulas vary. DHA, choline, and iron amounts are not consistent across '
                 'brands.',
  'image_url': '/static/images/prenatal-multivitamin.svg'},
 {'name': 'B-Complex',
  'category': 'Vitamin Formula',
  'keywords': ['b complex', 'energy support', 'methylated b vitamins'],
  'benefit': 'Combined B-vitamin support for energy metabolism and nervous system support',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': 'No single RDA; follow product label',
  'female_daily_intake': 'No single RDA; follow product label',
  'intake_note': 'Useful when multiple B vitamins are desired together, but high B6 doses should '
                 'be used cautiously.',
  'image_url': '/static/images/b-complex.svg'},
 {'name': 'Electrolyte Powder',
  'category': 'Hydration Supplement',
  'keywords': ['electrolytes', 'hydration', 'sodium', 'potassium', 'workout hydration'],
  'benefit': 'Hydration, sodium replacement, and exercise recovery support',
  'how_to_take': 'Mix with water according to the label, especially around exercise or heavy '
                 'sweating',
  'male_daily_intake': 'No established RDA for supplement powders; use based on sweat losses and '
                       'product label',
  'female_daily_intake': 'No established RDA for supplement powders; use based on sweat losses and '
                         'product label',
  'intake_note': 'Sugar, sodium, and potassium content vary widely. Some products are sports '
                 'drinks, others are low-calorie mixes.',
  'image_url': '/static/images/electrolyte-powder.svg'},
 {'name': 'Elderberry',
  'category': 'Herbal Supplement',
  'keywords': ['immune syrup', 'elderberry gummies', 'seasonal immune support'],
  'benefit': 'Seasonal immune support',
  'how_to_take': 'Take according to the label form, such as gummies, syrup, or capsules',
  'male_daily_intake': 'No established RDA; follow product dosing',
  'female_daily_intake': 'No established RDA; follow product dosing',
  'intake_note': 'Commonly marketed for immune support, but evidence and dosing quality vary by '
                 'product.',
  'image_url': '/static/images/elderberry.svg'},
 {'name': 'Cranberry',
  'category': 'Specialty Supplement',
  'keywords': ['urinary tract', 'uti support', 'cranberry extract', 'proanthocyanidins'],
  'benefit': 'Urinary tract support',
  'how_to_take': 'Take daily with water according to the label',
  'male_daily_intake': 'No established RDA; follow product dosing',
  'female_daily_intake': 'No established RDA; follow product dosing',
  'intake_note': 'This is often used for urinary support, but it does not replace evaluation or '
                 'treatment of an active infection.',
  'image_url': '/static/images/cranberry.svg'},
 {'name': 'Milk Thistle',
  'category': 'Herbal Supplement',
  'keywords': ['liver support', 'silymarin', 'detox support'],
  'benefit': 'Liver support and antioxidant support',
  'how_to_take': 'Take with food if it causes stomach upset',
  'male_daily_intake': 'No established RDA; follow standardized extract dosing on the label',
  'female_daily_intake': 'No established RDA; follow standardized extract dosing on the label',
  'intake_note': 'Marketed heavily for liver support, but it is still a supplement and can '
                 'interact with medications.',
  'image_url': '/static/images/milk-thistle.svg'},
 {'name': 'Greens Powder',
  'category': 'Functional Blend',
  'keywords': ['greens', 'superfood powder', 'vegetable blend', 'travel nutrition'],
  'benefit': 'Convenience support for produce intake and general wellness habits',
  'how_to_take': 'Mix with water or smoothies once daily',
  'male_daily_intake': 'No established RDA; follow product serving size',
  'female_daily_intake': 'No established RDA; follow product serving size',
  'intake_note': 'Useful for convenience, but it does not replace whole vegetables, fruit, and '
                 'adequate protein.',
  'image_url': '/static/images/greens-powder.svg'},
 {'name': 'Hair Skin and Nails Formula',
  'category': 'Beauty Supplement',
  'keywords': ['hair skin nails', 'beauty blend', 'biotin formula', 'collagen beauty'],
  'benefit': 'Hair, skin, and nail support',
  'how_to_take': 'Take once daily with food',
  'male_daily_intake': 'No single RDA; follow product label',
  'female_daily_intake': 'No single RDA; follow product label',
  'intake_note': 'These formulas often include biotin, zinc, vitamin C, or collagen. High biotin '
                 'can interfere with lab tests.',
  'image_url': '/static/images/hair-skin-and-nails-formula.svg'}]

collection.delete_many({})
collection.insert_many(data)

print(f"Supplement data reset complete. Inserted {len(data)} items.")

for item in collection.find():
    print(item)
